version: "3.8"
services:
  # The app service
  apk-releaser:
    # Rename it jizo to avoir being named `apk-releaser-1`
    container_name: apk_releaser_dev
    # Point to the dev.Dockerfile used for the build
    build:
      # dev.Dockerfile which is located in the same directory as the docker-compose.yaml
      context: .
      dockerfile: docker/dev.Dockerfile
    # Exposing ports
    ports:
      - "8008:8000"
    # Mount the volume
    volumes:
      - .:/usr/src
      - static_volume:/home/src/app/web/staticfiles
    # Cannot be launched without the db service fully working
    depends_on:
      - db
    # Link the network to the container
    networks:
      - apk-releaser
    # Hot reload (does not work, gotta work on it)
    restart: always

    # The database service
  db:
    # Using the postgreSQL official image
    image: postgres
    # Rename it postgres to avoid being named 'db-1'
    container_name: apk_releaser_postgres_dev
    # Define every required environment variables
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    # Create a volume to persist database data
    volumes:
      - pg_data:/var/lib/postgresql/data/
    # Link the network to the container
    networks:
      - apk-releaser
    # Always restart the database if it ever goes down
    restart: always

# List of networks
networks:
  apk-releaser:

volumes:
  pg_data:
  static_volume: