version: "3.8"
services:
  # The app service
  apk-releaser:
    # Rename it jizo to avoir being named `apk-releaser-1`
    container_name: apk_releaser_dev
    # Point to the dev.Dockerfile used for the build
    build:
      # dev.Dockerfile which is located in the same directory as the docker-compose.yaml
      context: .
      dockerfile: docker/prod.Dockerfile
    # Mount the volume
    volumes:
      - .:/usr/src
      - static_volume:/home/src/app/web/staticfiles
    # Cannot be launched without the db service fully working
    depends_on:
      - db
    # Link the network to the container
    networks:
      - apk-releaser
      - routing
    # Hot reload (does not work, gotta work on it)
    restart: always
    labels:
      # The labels are usefull for Traefik only
      - "traefik.enable=true"
      - "traefik.docker.network=routing"
      # API middlewares
      - "traefik.http.middlewares.apk-releaser-headers.headers.customresponseheaders.X-XSS-Protection=1; mode=block"
      - "traefik.http.middlewares.apk-releaser-headers.headers.customresponseheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.apk-releaser-headers.headers.customresponseheaders.X-Content-Type-Options=nosniff"
      - "traefik.http.middlewares.apk-releaser-headers.headers.customresponseheaders.Content-Security-Policy=frame-ancestors 'self'"
      - "traefik.http.middlewares.apk-releaser-headers.headers.customresponseheaders.Permission-Policy=interest-cohort=()"
      - "traefik.http.middlewares.apk-releaser-headers.headers.customresponseheaders.Strict-Transport-Security=max-age=31536000; includeSubDomains"
      # API
      - "traefik.http.routers.apk-releaser.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.apk-releaser.entrypoints=websecure"
      - "traefik.http.routers.apk-releaser.tls.certresolver=myresolver"
      - "traefik.http.routers.apk-releaser.middlewares=apk-releaser-headers"
      - "traefik.http.services.apk-releaser.loadbalancer.server.port=8000"
    tty: true
    command:
      gunicorn app.wsgi:application --bind 0.0.0.0:8000
    environment:
      - ALLOWED_HOSTS=${DOMAIN}

  # The database service
  db:
    # Using the postgreSQL official image
    image: postgres
    # Rename it postgres to avoid being named 'db-1'
    container_name: apk_releaser_postgres_dev
    # Define every required environment variables
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "5432:5432"
    # Create a volume to persist database data
    volumes:
      - pg_data:/var/lib/postgresql/data/
    # Link the network to the container
    networks:
      - apk-releaser
    # Always restart the database if it ever goes down
    restart: always

# List of networks
networks:
  apk-releaser:
  routing:
    external: true

volumes:
  pg_data:
  static_volume: