# Generated by Django 4.2.10 on 2024-04-01 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('release', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_android_apk', models.BooleanField(default=False)),
                ('is_ios_apk', models.BooleanField(default=False)),
                ('android_apk_url', models.CharField(blank=True, max_length=255, null=True)),
                ('ios_apk_url', models.CharField(blank=True, max_length=255, null=True)),
                ('android_apk_file', models.FileField(blank=True, null=True, upload_to='android_apk_file')),
                ('ios_apk_file', models.FileField(blank=True, null=True, upload_to='ios_apk_file')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InformationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apk.messagetype')),
            ],
        ),
    ]
