# Generated by Django 4.2.10 on 2024-04-01 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='apk',
            name='release',
        ),
        migrations.AlterField(
            model_name='informationmessage',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apk.messagetype'),
        ),
        migrations.AddField(
            model_name='apk',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apk.apktype'),
        ),
    ]
