# Generated by Django 4.2.10 on 2024-04-01 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apk', '0002_apktype_remove_apk_release_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apk',
            name='is_android_apk',
        ),
        migrations.RemoveField(
            model_name='apk',
            name='is_ios_apk',
        ),
        migrations.AlterField(
            model_name='apk',
            name='android_apk_file',
            field=models.FileField(blank=True, null=True, upload_to='static/android_apk_file'),
        ),
        migrations.AlterField(
            model_name='apk',
            name='ios_apk_file',
            field=models.FileField(blank=True, null=True, upload_to='static/ios_apk_file'),
        ),
    ]
